import {useEffect,useMemo,useState} from "react";
import {Background,Controls,Handle,Position,ReactFlow,type Edge,type Node,type NodeProps} from "@xyflow/react";

const API=import.meta.env.VITE_API_URL??"http://127.0.0.1:8100";
type Material={material_id:string;name:string;material_type:string;chemistry:{cao:number};evidence:{evidence_class:string}[]};
type Blend={blend_id:string;name:string;family:string;components:{material_id:string;percentage:number}[]};
type Machine={machine_id:string;name:string;machine_kind:string;process_stage:string;rated_capacity_tph:number;availability:number;specific_electricity_kwh_t:number;technology_readiness_level:number};
type Route={route_id:string;name:string;nodes:{node_id:string;machine_id:string;label:string;position_x:number;position_y:number}[];edges:{edge_id:string;source:string;target:string;stream_type:string}[]};
type Result={run_id:string;achievable_output_tph:number;bottleneck_tph:number;electricity_kwh_t:number;thermal_kcal_kg:number;material_cost_inr_t:number;energy_cost_inr_t:number;estimated_co2_kg_t:number;lsf:number|null;warnings:string[];events:{sequence:number;elapsed_seconds:number;level:string;component:string;message:string}[]};
async function req<T>(path:string,options?:RequestInit):Promise<T>{const r=await fetch(API+path,{headers:{"Content-Type":"application/json"},...options});if(!r.ok)throw new Error(await r.text());return r.json()}
function PNode({data}:NodeProps){const d=data as {label:string;stage:string;capacity:number;energy:number;active:boolean;warning:boolean};return <div className={`pnode ${d.active?"active":""} ${d.warning?"warning":""}`}><Handle type="target" position={Position.Left}/><small>{d.stage}</small><strong>{d.label}</strong><span>{d.capacity.toFixed(1)} t/h</span><span>{d.energy.toFixed(1)} kWh/t</span><Handle type="source" position={Position.Right}/></div>}
const nodeTypes={process:PNode};
export function App(){
 const [view,setView]=useState("console"),[materials,setMaterials]=useState<Material[]>([]),[blends,setBlends]=useState<Blend[]>([]),[machines,setMachines]=useState<Machine[]>([]),[routes,setRoutes]=useState<Route[]>([]),[blendId,setBlendId]=useState(""),[routeId,setRouteId]=useState(""),[target,setTarget]=useState(100),[result,setResult]=useState<Result|null>(null),[visible,setVisible]=useState(0),[error,setError]=useState("");
 async function load(){const [a,b,c,d]=await Promise.all([req<Material[]>("/api/materials"),req<Blend[]>("/api/blends"),req<Machine[]>("/api/machines"),req<Route[]>("/api/routes")]);setMaterials(a);setBlends(b);setMachines(c);setRoutes(d);setBlendId(x=>x||b[0]?.blend_id||"");setRouteId(x=>x||d[0]?.route_id||"")}
 useEffect(()=>{load().catch(e=>setError(String(e)))},[]);useEffect(()=>{if(result&&visible<result.events.length){const t=setTimeout(()=>setVisible(x=>x+1),100);return()=>clearTimeout(t)}},[result,visible]);
 const route=routes.find(x=>x.route_id===routeId),machineMap=useMemo(()=>new Map(machines.map(x=>[x.machine_id,x])),[machines]),active=new Set(result?.events.slice(0,visible).map(x=>x.component)||[]);
 const nodes:Node[]=(route?.nodes||[]).map(n=>{const m=machineMap.get(n.machine_id);return{id:n.node_id,type:"process",position:{x:n.position_x,y:n.position_y},draggable:false,data:{label:n.label,stage:m?.process_stage||"unknown",capacity:(m?.rated_capacity_tph||0)*(m?.availability||0),energy:m?.specific_electricity_kwh_t||0,active:active.has(n.machine_id),warning:result?.warnings.some(w=>w.includes(m?.name||"___"))||false}}});
 const edges:Edge[]=(route?.edges||[]).map(e=>({id:e.edge_id,source:e.source,target:e.target,animated:!!result}));
 async function run(){setError("");setVisible(0);setResult(await req<Result>("/api/runs",{method:"POST",body:JSON.stringify({blend_id:blendId,route_id:routeId,target_output_tph:target})}))}
 return <main><header><b>BRIXTA CEMENT TWIN LAB</b><span>{result?.run_id||"NO ACTIVE RUN"}</span><nav>{["console","blend","machine","route","library"].map(x=><button className={view===x?"selected":""} onClick={()=>setView(x)} key={x}>{x.toUpperCase()}</button>)}</nav></header>
 {view==="console"&&<><section className="config"><label>BLEND<select value={blendId} onChange={e=>setBlendId(e.target.value)}>{blends.map(x=><option value={x.blend_id}>{x.name}</option>)}</select></label><label>ROUTE<select value={routeId} onChange={e=>setRouteId(e.target.value)}>{routes.map(x=><option value={x.route_id}>{x.name}</option>)}</select></label><label>TARGET T/H<input type="number" value={target} onChange={e=>setTarget(Number(e.target.value))}/></label><button className="run" onClick={()=>run().catch(e=>setError(String(e)))}>RUN SIMULATION</button></section>{error&&<div className="err">{error}</div>}<section className="workspace"><div className="topology"><div className="title">PROCESS TOPOLOGY / MATERIAL FLOW</div><ReactFlow nodes={nodes} edges={edges} nodeTypes={nodeTypes} fitView proOptions={{hideAttribution:true}}><Background gap={28}/><Controls/></ReactFlow></div><div className="logs"><div className="title">EVENT STREAM</div>{(result?.events||[]).slice(0,visible).map(x=><div className={`log ${x.level}`}><span>{x.elapsed_seconds.toFixed(2)}</span><span>{x.level}</span><span>{x.component}</span><span>{x.message}</span></div>)}</div></section><section className="signals">{result?[['OUTPUT',`${result.achievable_output_tph.toFixed(1)} t/h`],['BOTTLENECK',`${result.bottleneck_tph.toFixed(1)} t/h`],['ELECTRICITY',`${result.electricity_kwh_t.toFixed(1)} kWh/t`],['THERMAL',`${result.thermal_kcal_kg.toFixed(1)} kcal/kg`],['MATERIAL',`₹${result.material_cost_inr_t.toFixed(0)}/t`],['ENERGY',`₹${result.energy_cost_inr_t.toFixed(0)}/t`],['CO2',`${result.estimated_co2_kg_t.toFixed(0)} kg/t`],['LSF',result.lsf?.toFixed(3)||'N/A']].map(x=><div><small>{x[0]}</small><b>{x[1]}</b></div>):<span>AWAITING RUN</span>}</section></>}
 {view==="blend"&&<BlendGuide materials={materials} done={x=>{setBlends(v=>[...v,x]);setBlendId(x.blend_id);setView("console")}}/>}
 {view==="machine"&&<MachineGuide done={x=>{setMachines(v=>[...v,x]);setView("route")}}/>}
 {view==="route"&&<RouteGuide machines={machines} routes={routes} done={x=>{setRoutes(v=>[...v,x]);setRouteId(x.route_id);setView("console")}}/>}
 {view==="library"&&<section className="library"><div className="title">MATERIAL LIBRARY</div>{materials.map(x=><p><code>{x.material_id}</code> {x.name} · {x.chemistry.cao}% CaO · {x.evidence[0]?.evidence_class||'unverified'}</p>)}<div className="title">MACHINE LIBRARY</div>{machines.map(x=><p><code>{x.machine_id}</code> {x.name} · {x.rated_capacity_tph} t/h · TRL {x.technology_readiness_level}</p>)}</section>}</main>}
function BlendGuide({materials,done}:{materials:Material[];done:(x:Blend)=>void}){const [name,setName]=useState("New PPC Candidate"),[parts,setParts]=useState([{material_id:materials[1]?.material_id||"",percentage:64},{material_id:materials[2]?.material_id||"",percentage:31},{material_id:materials[3]?.material_id||"",percentage:5}]),total=parts.reduce((a,b)=>a+b.percentage,0);async function save(){done(await req<Blend>("/api/blends",{method:"POST",body:JSON.stringify({name,family:"PPC",objective:"controlled_improvement",applicable_standard:"Review required",components:parts,evidence:[]})}))}return <section className="guide"><h2>GUIDE / NEW BLEND</h2><label>NAME<input value={name} onChange={e=>setName(e.target.value)}/></label>{parts.map((p,i)=><div className="row"><select value={p.material_id} onChange={e=>setParts(v=>v.map((x,j)=>j===i?{...x,material_id:e.target.value}:x))}>{materials.map(m=><option value={m.material_id}>{m.name}</option>)}</select><input type="number" value={p.percentage} onChange={e=>setParts(v=>v.map((x,j)=>j===i?{...x,percentage:Number(e.target.value)}:x))}/><span>%</span></div>)}<pre>{Math.abs(total-100)<.01?"PASS  Component total = 100.00%\nWARN  Physical validation not attached":"FAIL  Component total = "+total.toFixed(2)+"%"}</pre><button className="run" disabled={Math.abs(total-100)>.01} onClick={()=>save()}>CREATE VERSIONED BLEND</button></section>}
function MachineGuide({done}:{done:(x:Machine)=>void}){const [kind,setKind]=useState("standard"),[name,setName]=useState("New Process Machine"),[stage,setStage]=useState("cement_grinding"),[capacity,setCapacity]=useState(100),[energy,setEnergy]=useState(20),[trl,setTrl]=useState(5);async function save(){const base={machine_kind:kind,name,process_stage:stage,rated_capacity_tph:capacity,minimum_stable_tph:capacity*.4,availability:.9,specific_electricity_kwh_t:energy,specific_heat_kcal_kg:0,capex_inr_crore:0,technology_readiness_level:trl,evidence:[]};done(await req<Machine>("/api/machines",{method:"POST",body:JSON.stringify(kind==="thermal"?{...base,maximum_temperature_c:1450,residence_time_minutes:30,conversion_fraction:.95,product_state:"clinker"}:{...base,input_material:"solid",output_material:"solid"})}))}return <section className="guide"><h2>GUIDE / NEW MACHINE</h2><label>TYPE<select value={kind} onChange={e=>setKind(e.target.value)}><option value="standard">Standard</option><option value="thermal">Thermal transformation</option></select></label><label>NAME<input value={name} onChange={e=>setName(e.target.value)}/></label><label>STAGE<select value={stage} onChange={e=>setStage(e.target.value)}><option value="crushing">Crushing</option><option value="raw_grinding">Raw grinding</option><option value="thermal_transformation">Thermal transformation</option><option value="cement_grinding">Cement grinding</option><option value="packing_dispatch">Packing</option></select></label><div className="row"><label>CAPACITY<input type="number" value={capacity} onChange={e=>setCapacity(Number(e.target.value))}/></label><label>KWH/T<input type="number" value={energy} onChange={e=>setEnergy(Number(e.target.value))}/></label><label>TRL<input type="number" min="1" max="9" value={trl} onChange={e=>setTrl(Number(e.target.value))}/></label></div><pre>{trl>=8?"PASS  Commercial maturity threshold":"WARN  TRL below 8\nBLOCK Investor base case; allow R&D only"}</pre><button className="run" onClick={()=>save()}>CREATE MACHINE</button></section>}
function RouteGuide({machines,routes,done}:{machines:Machine[];routes:Route[];done:(x:Route)=>void}){const [rid,setRid]=useState(routes[0]?.route_id||""),route=routes.find(x=>x.route_id===rid),[nid,setNid]=useState(route?.nodes[0]?.node_id||""),[mid,setMid]=useState(machines[0]?.machine_id||"");const old=machines.find(x=>x.machine_id===route?.nodes.find(n=>n.node_id===nid)?.machine_id),next=machines.find(x=>x.machine_id===mid),ok=old?.process_stage===next?.process_stage;async function save(){if(!route)return;done(await req<Route>("/api/routes",{method:"POST",body:JSON.stringify({name:`${route.name} / ${next?.name}`,nodes:route.nodes.map(n=>n.node_id===nid?{...n,machine_id:mid,label:next?.name||n.label}:n),edges:route.edges})}))}return <section className="guide"><h2>GUIDE / PIN MACHINE INTO ROUTE</h2><label>BASE ROUTE<select value={rid} onChange={e=>setRid(e.target.value)}>{routes.map(x=><option value={x.route_id}>{x.name}</option>)}</select></label><label>NODE<select value={nid} onChange={e=>setNid(e.target.value)}>{route?.nodes.map(x=><option value={x.node_id}>{x.label}</option>)}</select></label><label>REPLACEMENT<select value={mid} onChange={e=>setMid(e.target.value)}>{machines.map(x=><option value={x.machine_id}>{x.name} / {x.process_stage}</option>)}</select></label><pre>- {old?.name}\n+ {next?.name}\n{ok?"PASS  Process stage compatible":"FAIL  Process stage mismatch"}</pre><button className="run" disabled={!ok} onClick={()=>save()}>CREATE MACHINE-SWAP ROUTE</button></section>}
